### ISSUE TITLE
Basket allows users to add the same ticket twice

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jamesread/lan-party-site#54]
```
I've had a paypal payment which contains two line items for the same ticket, ie 
the punter has bought the same ticket twice, and paid double for it.

While this is their own fault, perhaps validation would be a good idea
```

Original issue reported on code.google.com by `thewi...@gmail.com` on 24 Oct 2012 at 7:50

**Comment by jamesread** [comment]
The following events logic now has been working for some time. 

     public static function getPayableEvents() {
         $events = self::getSignupableEvents();
         $events = self::removeEventsUnpayable($events);
         $events = self::removeEventsAlreadyInBasket($events);
         $events = self::removeEventsAlreadySignedupFor($events);
