### ISSUE TITLE
Move people around seating plan

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jamesread/lan-party-site#58]
```
James on the Seating plan could you make it possible to add people, not just 
move them? 
```

Original issue reported on code.google.com by `xconspir...@gmail.com` on 4 May 2013 at 6:34

**Comment by jamesread** [comment]
You've been able to do this for a while ;) 

![image](https://user-images.githubusercontent.com/2025715/30150906-24e66982-93a5-11e7-8f64-274e9107ceca.png)
