### ISSUE TITLE
Can't pay for 2 people

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jamesread/lan-party-site#70]
```
Can't pay for 2 people

I just made a payment with paypal for two people, one is for me the other is 
for Stormwire (Arran Wilkins).
The paying page did not seem to work, it would only add my username.
```

Original issue reported on code.google.com by `xconspir...@gmail.com` on 10 Feb 2014 at 9:08

**Comment by jamesread** [comment]
You can now! 

![image](https://user-images.githubusercontent.com/2025715/30150854-f46b2d56-93a4-11e7-84ca-1dda7f708270.png)
